import React, { useState, useEffect } from 'react';
import { RiAddLine, RiDeleteBinLine, RiFilePdfLine, RiFileExcelLine, RiCheckLine, RiCalendarLine } from 'react-icons/ri';
import api from '../api/axios';
import { useAuth } from '../context/AuthContext';
import { formatCurrency, monthNames, getCurrentMonthYear } from '../utils/helpers';
import ConfirmModal from '../components/ConfirmModal';

export default function Billing() {
  const { user } = useAuth();
  const curr = user?.currency || 'PKR';
  const { month: cm, year: cy } = getCurrentMonthYear();

  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [genMonth, setGenMonth] = useState(cm);
  const [genYear, setGenYear] = useState(cy);
  const [deleteId, setDeleteId] = useState(null);

  useEffect(() => {
    api.get('/bills').then(r => setBills(r.data.data)).catch(console.error).finally(() => setLoading(false));
  }, []);

  const generateBill = async () => {
    setGenerating(true);
    try {
      const { data } = await api.post('/bills', { month: genMonth, year: genYear });
      setBills(prev => {
        const exists = prev.findIndex(b => b.month === data.data.month && b.year === data.data.year);
        if (exists >= 0) { const a = [...prev]; a[exists] = data.data; return a; }
        return [data.data, ...prev];
      });
    } catch (e) { alert(e.response?.data?.message || 'Error generating bill'); }
    finally { setGenerating(false); }
  };

  const handleDelete = async () => {
    await api.delete(`/bills/${deleteId}`);
    setBills(prev => prev.filter(b => b._id !== deleteId));
    setDeleteId(null);
  };

  const markPaid = async (id) => {
    const { data } = await api.patch(`/bills/${id}`, { status: 'paid' });
    setBills(prev => prev.map(b => b._id === id ? data.data : b));
  };

  const exportPDF = async (bill) => {
    const { default: jsPDF } = await import('jspdf');
    const { default: autoTable } = await import('jspdf-autotable');

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageW = doc.internal.pageSize.width;

    // Header gradient bar
    doc.setFillColor(79, 156, 249);
    doc.rect(0, 0, pageW, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22); doc.setFont('helvetica', 'bold');
    doc.text('DOODH LEDGER', 20, 18);
    doc.setFontSize(11); doc.setFont('helvetica', 'normal');
    doc.text('Household Expense Bill', 20, 27);
    doc.text(`Bill #${bill.billNumber}`, pageW - 20, 18, { align: 'right' });

    // Bill meta
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(11); doc.setFont('helvetica', 'bold');
    doc.text('Bill To:', 20, 55);
    doc.setFont('helvetica', 'normal');
    doc.text(user?.name || 'Customer', 20, 63);
    if (user?.phone) doc.text(user.phone, 20, 70);
    if (user?.address) doc.text(user.address, 20, 77);

    doc.setFont('helvetica', 'bold');
    doc.text('Period:', pageW - 80, 55);
    doc.setFont('helvetica', 'normal');
    doc.text(`${monthNames[bill.month - 1]} ${bill.year}`, pageW - 80, 63);
    doc.text(`Generated: ${new Date(bill.createdAt).toLocaleDateString()}`, pageW - 80, 70);
    doc.text(`Status: ${bill.status.toUpperCase()}`, pageW - 80, 77);

    // Items table
    const rows = [];
    if (bill.milkLiters > 0) rows.push(['🥛 Milk', bill.milkSupplier || '—', `${bill.milkLiters.toFixed(2)} L`, `${curr} ${bill.milkCharges.toLocaleString()}`]);
    if (bill.waterCans > 0)  rows.push(['💧 Water', bill.waterSupplier || '—', `${bill.waterCans} Cans`, `${curr} ${bill.waterCharges.toLocaleString()}`]);
    if (bill.gasCylinders > 0) rows.push(['🔥 Gas', bill.gasSupplier || '—', `${bill.gasCylinders} Cyl.`, `${curr} ${bill.gasCharges.toLocaleString()}`]);

    autoTable(doc, {
      startY: 90,
      head: [['Item', 'Supplier', 'Quantity', 'Amount']],
      body: rows,
      theme: 'grid',
      headStyles: { fillColor: [79, 156, 249], textColor: 255, fontStyle: 'bold', fontSize: 11 },
      bodyStyles: { fontSize: 10.5, textColor: [40, 40, 40] },
      alternateRowStyles: { fillColor: [245, 248, 255] },
      columnStyles: { 3: { halign: 'right', fontStyle: 'bold' } },
      margin: { left: 20, right: 20 },
    });

    const finalY = doc.lastAutoTable.finalY + 10;

    // Grand total
    doc.setFillColor(240, 245, 255);
    doc.rect(pageW - 90, finalY, 70, 20, 'F');
    doc.setFont('helvetica', 'bold'); doc.setFontSize(13);
    doc.setTextColor(79, 156, 249);
    doc.text('GRAND TOTAL', pageW - 88, finalY + 8);
    doc.setFontSize(14);
    doc.text(`${curr} ${bill.grandTotal.toLocaleString()}`, pageW - 22, finalY + 14, { align: 'right' });

    // Footer
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Doodh Ledger — doodh-ledger.app', pageW / 2, 285, { align: 'center' });

    doc.save(`Bill-${monthNames[bill.month - 1]}-${bill.year}.pdf`);
  };

  const exportBillCSV = (bill) => {
    const rows = [
      { Item: 'Milk', Supplier: bill.milkSupplier, Quantity: `${bill.milkLiters} L`, Amount: bill.milkCharges },
      { Item: 'Water', Supplier: bill.waterSupplier, Quantity: `${bill.waterCans} Cans`, Amount: bill.waterCharges },
      { Item: 'Gas', Supplier: bill.gasSupplier, Quantity: `${bill.gasCylinders} Cyl.`, Amount: bill.gasCharges },
      { Item: 'GRAND TOTAL', Supplier: '', Quantity: '', Amount: bill.grandTotal },
    ];
    const keys = Object.keys(rows[0]);
    const csv = [keys.join(','), ...rows.map(r => keys.map(k => `"${r[k] ?? ''}"`).join(','))].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob);
    a.download = `Bill-${monthNames[bill.month-1]}-${bill.year}.csv`; a.click();
  };

  const statusColors = { draft: '#fbbf24', generated: '#4f9cf9', paid: '#34d399' };

  return (
    <div className="fade-in">
      <div className="page-header d-flex align-items-center justify-content-between flex-wrap gap-3">
        <div><h1>📄 Billing</h1><p>Generate and manage monthly bills</p></div>
      </div>

      {/* Generate Bill Panel */}
      <div className="glass-card mb-4" style={{ padding: 28 }}>
        <h5 style={{ fontWeight: 700, marginBottom: 20 }}>Generate Monthly Bill</h5>
        <div className="d-flex align-items-center gap-3 flex-wrap">
          <RiCalendarLine style={{ color: 'var(--primary)', fontSize: '1.2rem' }} />
          <select value={genMonth} onChange={e => setGenMonth(Number(e.target.value))} className="form-control-dark" style={{ width: 150 }}>
            {monthNames.map((m, i) => <option key={i} value={i+1}>{m}</option>)}
          </select>
          <select value={genYear} onChange={e => setGenYear(Number(e.target.value))} className="form-control-dark" style={{ width: 100 }}>
            {[cy-1, cy, cy+1].map(y => <option key={y} value={y}>{y}</option>)}
          </select>
          <button onClick={generateBill} className="btn-primary-custom" disabled={generating}
            style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <RiAddLine />{generating ? 'Generating...' : 'Generate Bill'}
          </button>
        </div>
        <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)', marginTop: 12 }}>
          This will compile all milk, water and gas entries for the selected month into a bill.
        </p>
      </div>

      {/* Bills List */}
      {loading ? (
        <div className="d-flex justify-content-center p-5"><div className="spinner-ring" /></div>
      ) : bills.length === 0 ? (
        <div className="empty-state glass-card" style={{ padding: 60 }}>
          <RiFilePdfLine />
          <h5>No bills generated yet</h5>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>Select a month above and click "Generate Bill"</p>
        </div>
      ) : (
        <div className="row g-3 stagger">
          {bills.map(bill => (
            <div key={bill._id} className="col-lg-6">
              <div className="glass-card" style={{ padding: 24 }}>
                {/* Bill Header */}
                <div className="d-flex justify-content-between align-items-start mb-4">
                  <div>
                    <h5 style={{ fontWeight: 700, margin: 0 }}>
                      {monthNames[bill.month - 1]} {bill.year}
                    </h5>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: 4 }}>#{bill.billNumber}</div>
                  </div>
                  <span style={{
                    background: statusColors[bill.status] + '20',
                    color: statusColors[bill.status],
                    border: `1px solid ${statusColors[bill.status]}40`,
                    borderRadius: 8, padding: '4px 12px', fontSize: '0.78rem', fontWeight: 700
                  }}>{bill.status.toUpperCase()}</span>
                </div>

                {/* Line items */}
                <div style={{ borderTop: '1px solid var(--border)', paddingTop: 16 }}>
                  {[
                    { label: '🥛 Milk', qty: `${bill.milkLiters?.toFixed(1)} L`, amount: bill.milkCharges, supplier: bill.milkSupplier },
                    { label: '💧 Water', qty: `${bill.waterCans} Cans`, amount: bill.waterCharges, supplier: bill.waterSupplier },
                    { label: '🔥 Gas', qty: `${bill.gasCylinders} Cyl.`, amount: bill.gasCharges, supplier: bill.gasSupplier },
                  ].map((item, i) => (
                    <div key={i} className="d-flex justify-content-between align-items-center mb-3">
                      <div>
                        <div style={{ fontWeight: 600, fontSize: '0.9rem' }}>{item.label}</div>
                        <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>{item.qty}{item.supplier ? ` · ${item.supplier}` : ''}</div>
                      </div>
                      <div style={{ fontWeight: 600, fontSize: '0.95rem' }}>{formatCurrency(item.amount, curr)}</div>
                    </div>
                  ))}
                </div>

                {/* Grand Total */}
                <div style={{
                  borderTop: '2px solid var(--border)', marginTop: 8, paddingTop: 16,
                  display: 'flex', justifyContent: 'space-between', alignItems: 'center'
                }}>
                  <span style={{ fontWeight: 800, fontSize: '1rem' }}>Grand Total</span>
                  <span style={{ fontWeight: 800, fontSize: '1.3rem', color: 'var(--primary)' }}>
                    {formatCurrency(bill.grandTotal, curr)}
                  </span>
                </div>

                {/* Actions */}
                <div className="d-flex gap-2 mt-4 flex-wrap">
                  <button onClick={() => exportPDF(bill)} style={{
                    flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
                    background: 'rgba(248,113,113,0.1)', border: '1px solid rgba(248,113,113,0.2)',
                    borderRadius: 10, color: '#f87171', padding: '10px', cursor: 'pointer', fontWeight: 600, fontSize: '0.85rem'
                  }}><RiFilePdfLine /> PDF</button>
                  <button onClick={() => exportBillCSV(bill)} style={{
                    flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
                    background: 'rgba(52,211,153,0.1)', border: '1px solid rgba(52,211,153,0.2)',
                    borderRadius: 10, color: '#34d399', padding: '10px', cursor: 'pointer', fontWeight: 600, fontSize: '0.85rem'
                  }}><RiFileExcelLine /> CSV</button>
                  {bill.status !== 'paid' && (
                    <button onClick={() => markPaid(bill._id)} style={{
                      flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
                      background: 'rgba(52,211,153,0.1)', border: '1px solid rgba(52,211,153,0.2)',
                      borderRadius: 10, color: '#34d399', padding: '10px', cursor: 'pointer', fontWeight: 600, fontSize: '0.85rem'
                    }}><RiCheckLine /> Paid</button>
                  )}
                  <button onClick={() => setDeleteId(bill._id)} style={{
                    width: 40, display: 'flex', alignItems: 'center', justifyContent: 'center',
                    background: 'rgba(248,113,113,0.1)', border: '1px solid rgba(248,113,113,0.2)',
                    borderRadius: 10, color: '#f87171', padding: '10px', cursor: 'pointer'
                  }}><RiDeleteBinLine /></button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {deleteId && (
        <ConfirmModal message="Delete this bill permanently?" onConfirm={handleDelete} onClose={() => setDeleteId(null)} />
      )}
    </div>
  );
}
